"""Hephaestus Engine for Aura.

Automates the synthesis, validation, and registration of new Python skills 
to expand Aura's capabilities autonomously.
"""
import asyncio
import inspect
import logging
import os
import textwrap
from pathlib import Path
from typing import Any, Dict, List, Optional, Type

from core.base_module import AuraBaseModule
from core.container import ServiceContainer
from core.config import config

SKILL_TEMPLATE = """
\"\"\"Autogenerated Skill: {name}\"\"\"
from typing import Any, Dict
from core.capability_engine import AuraSkill

class {class_name}(AuraSkill):
    \"\"\"{description}\"\"\"
    
    async def execute(self, params: Dict[str, Any], context: Dict[str, Any] = None) -> Dict[str, Any]:
        \"\"\"{logic_description}\"\"\"
        try:
            # --- START AUTOGENERATED LOGIC ---
{logic_code}
            # --- END AUTOGENERATED LOGIC ---
        except Exception as e:
            return {{"ok": False, "error": str(e)}}
"""

class HephaestusEngine(AuraBaseModule):
    """The Forge of Capabilities."""
    
    def __init__(self):
        """Initializes the HephaestusEngine."""
        super().__init__("Hephaestus")
        self.skills_dir = config.paths.project_root / "skills"
        self.skills_dir.mkdir(parents=True, exist_ok=True)
        self.logger.info("🔨 Hephaestus Engine Online (Autogenesis Forge Ready)")

    async def synthesize_skill(self, capability_name: str, objective: str) -> Dict[str, Any]:
        """Generates a new skill from a description."""
        @self.error_boundary
        async def _synthesize_wrapped():
            self.logger.info("🔨 Forging skill: %s for objective: %s", capability_name, objective)
            
            # 1. Draft Logic with LLM
            logic_data = await self._draft_logic(capability_name, objective)
            if not logic_data.get("ok"):
                return logic_data

            # 2. Assemble Code
            class_name = "".join(x.capitalize() for x in capability_name.split("_"))
            code = SKILL_TEMPLATE.format(
                name=capability_name,
                class_name=class_name,
                description=logic_data.get("description", "Autogenerated Capability"),
                logic_description=logic_data.get("logic_description", "Performs the requested task."),
                logic_code=textwrap.indent(logic_data["code"], "            ")
            )

            # 3. Path Management
            skill_file = self.skills_dir / f"{capability_name}.py"
            
            # 4. Sandbox Validation (Syntax Check)
            try:
                compile(code, str(skill_file), 'exec')
            except SyntaxError as e:
                return {"ok": False, "error": f"Syntax error in generated code: {e}"}

            # 5. Save to Disk
            with open(skill_file, "w") as f:
                f.write(code)
                
            self.logger.info("✅ Skill '%s' forged and saved.", capability_name)
            
            # 6. Trigger Discovery
            engine = ServiceContainer.get("capability_engine")
            if engine:
                await engine.discover_skills()
                
            return {"ok": True, "path": str(skill_file), "capability": capability_name}

        return await _synthesize_wrapped()

    async def _draft_logic(self, name: str, objective: str) -> Dict[str, Any]:
        """Uses the LLM to write the core execution logic for the skill."""
        brain = ServiceContainer.get("cognitive_engine")
        if not brain:
            return {"ok": False, "error": "Cognitive engine unavailable."}

        if not objective:
            objective = "Performs a general task without a specific objective provided."

        prompt = (
            f"Write a Python function body for a skill named '{name}' that accomplishes: '{objective}'.\n"
            f"Return ONLY the Python code block. No markdown, no triple backticks, no comments outside the logic.\n"
            f"The logic should be robust and return a Dict[str, Any] with 'ok' and results.\n"
            f"Import any necessary standard libraries INSIDE the logic block."
        )
        
        try:
            res = await brain.think(prompt)
            code = res.content
            # Cleanup common LLM markdown contamination
            if "```python" in code:
                code = code.split("```python")[1].split("```")[0]
            elif "```" in code:
                code = code.split("```")[1].split("```")[0]
            
            # Strip any remaining leading/trailing markdown-style comments or clutter
            lines = code.strip().split('\n')
            clean_lines = []
            for line in lines:
                if line.strip().startswith("```"): continue
                clean_lines.append(line)
            code = '\n'.join(clean_lines)

            return {
                "ok": True, 
                "code": code.strip(),
                "description": f"Autogenerated skill for {objective}",
                "logic_description": objective
            }
        except Exception as e:
            return {"ok": False, "error": f"LLM logic generation failed: {e}"}

    def get_health(self) -> Dict[str, Any]:
        """Provides health info for Hephaestus."""
        return {
            **super().get_health(),
            "forge_count": len(list(self.skills_dir.glob("*.py")))
        }
